class SFMegaPlayer : NetNaviPlayer
{
	Default
	{
//		NetNaviPlayer.EmotionFace "BASSFAC";
		Player.DisplayName "SF MegaMan";
		Player.StartItem "SFMegaBuster";
		Player.WeaponSlot 1, "SFMegaBuster";
		Player.SoundClass "megaman";
		Player.Portrait "SFMMFAC1";
	}
	States
	{
		Spawn:
			BMEG A -1 A_SetTranslucent(1.00);
			Loop;
		See:
			BMEG BCDEFG 4;
			Loop;
		Missile:
			BMEG H 2;
			BMEG IJ 2 Bright;
			BMEG H 1;
			Goto Spawn;
		Pain:
			BMEG K 3 Bright;
			BMEG L 3 A_Pain;
			BMEG M 3;
			Goto Spawn;
		Death:
			BMEG N 7;
			BMEG O 7 A_NoBlocking;
			BMEG P 2 Bright;
			BMEG O 2;
			BMEG P 2 Bright;
			BMEG O 2;
			BMEG P 2 Bright;
			BMEG O 30 A_SpawnItem("BN6DeathEffect", 0, 27, 0); // I had to make this an object instead of an overlay because overlays just... weren't working.
			BMEG P 10 Bright A_PlayerScream;
			BMEG P 3 Bright A_SetTranslucent(0.90);
			BMEG P 3 Bright A_SetTranslucent(0.80);
			BMEG P 3 Bright A_SetTranslucent(0.70);
			BMEG P 3 Bright A_SetTranslucent(0.60);
			BMEG P 3 Bright A_SetTranslucent(0.50);
			BMEG P 3 Bright A_SetTranslucent(0.40);
			BMEG P 3 Bright A_SetTranslucent(0.30);
			BMEG P 3 Bright A_SetTranslucent(0.20);
			BMEG P 3 Bright A_SetTranslucent(0.10);
			BMEG P 3 Bright A_SetTranslucent(0.00);
			TNT1 A -1;
			Stop;
	}
}